[package]
name = "spo2"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
arraydeque = "0.4.5"
futures-locks = "0.4.0"
futures-preview = "0.3.0-alpha.18"
futures-timer = "0.4.0"
once_cell = "1.0.2"
serde_json = "1.0.40"
surf = "1.0.2"
url = "2.1.0"

[dependencies.redismodule]
git = "https://github.com/Kerollmops/redismodule-rs.git"
branch = "redisvalue-from-reply"
# path = "../redismodule-rs"
features = ["experimental-api"]
