[package]
name = "spo2"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies.redismodule]
git = "https://github.com/RedisLabsModules/redismodule-rs.git"
tag = "v0.4.0"
